name: "[CI] Core"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-api/**"
      - "decidim-core/**"
      - "decidim-dev/**"
      - "packages/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_app:
    uses: ./.github/workflows/build_app.yml
    secrets: inherit
    name: Build test application
  main:
    strategy:
      fail-fast: false
      matrix:
        test-command:
          - bundle exec parallel_test --type rspec --pattern spec/commands
          - bundle exec parallel_test --type rspec --pattern spec/content_parsers
          - bundle exec parallel_test --type rspec --pattern spec/content_renderers
          - bundle exec parallel_test --type rspec --pattern spec/controllers
          - bundle exec parallel_test --type rspec --pattern spec/db
          - bundle exec parallel_test --type rspec --pattern spec/events
          - bundle exec parallel_test --type rspec --pattern spec/forms
          - bundle exec parallel_test --type rspec --pattern spec/helpers
          - bundle exec parallel_test --type rspec --pattern spec/jobs
          - bundle exec parallel_test --type rspec --pattern spec/js
          - bundle exec parallel_test --type rspec --pattern spec/mailers
          - bundle exec parallel_test --type rspec --pattern spec/models
          - bundle exec parallel_test --type rspec --pattern spec/permissions
          - bundle exec parallel_test --type rspec --pattern spec/presenters
          - bundle exec parallel_test --type rspec --pattern spec/queries
          - bundle exec parallel_test --type rspec --pattern spec/requests
          - bundle exec parallel_test --type rspec --pattern spec/routing
          - bundle exec parallel_test --type rspec --pattern spec/scrubbers
          - bundle exec parallel_test --type rspec --pattern spec/serializers
          - bundle exec parallel_test --type rspec --pattern spec/services
          - bundle exec parallel_test --type rspec --pattern spec/tasks
          - bundle exec parallel_test --type rspec --pattern spec/types
          - bundle exec parallel_test --type rspec --pattern spec/uploaders
          - bundle exec parallel_test --type rspec --pattern spec/validators
          - bundle exec parallel_test --type rspec --pattern spec/lib
          - bundle exec parallel_test --type rspec --pattern spec/system
          - bundle exec parallel_test --type rspec --pattern spec/ --exclude-pattern 'spec/(commands|content_parsers|content_renderers|controllers|db|events|forms|helpers|jobs|js|lib|mailers|models|permissions|presenters|queries|requests|routing|scrubbers|serializers|services|system|tasks|types|uploaders|validators)'
    needs: build_app
    name: Tests
    uses: ./.github/workflows/test_app.yml
    secrets: inherit
    with:
      working-directory: "decidim-core"
      test_command: ${{ matrix.test-command }}

