name: "[CI] Proposals"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-admin/**"
      - "decidim-assemblies/**"
      - "decidim-budgets/**"
      - "decidim-comments/**"
      - "decidim-core/**"
      - "decidim-dev/**"
      - "decidim-meetings/**"
      - "decidim-participatory_processes/**"
      - "decidim-proposals/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_app:
    uses: ./.github/workflows/build_app.yml
    secrets: inherit
    name: Build test application

  main:
    strategy:
      fail-fast: false
      matrix:
        test-command:
          - bundle exec parallel_test --type rspec --pattern spec/cells
          - bundle exec parallel_test --type rspec --pattern spec/commands
          - bundle exec parallel_test --type rspec --pattern spec/controllers
          - bundle exec parallel_test --type rspec --pattern spec/events
          - bundle exec parallel_test --type rspec --pattern spec/forms
          - bundle exec parallel_test --type rspec --pattern spec/helpers
          - bundle exec parallel_test --type rspec --pattern spec/jobs
          - bundle exec parallel_test --type rspec --pattern spec/lib
          - bundle exec parallel_test --type rspec --pattern spec/models
          - bundle exec parallel_test --type rspec --pattern spec/permissions
          - bundle exec parallel_test --type rspec --pattern spec/presenters
          - bundle exec parallel_test --type rspec --pattern spec/queries
          - bundle exec parallel_test --type rspec --pattern spec/requests
          - bundle exec parallel_test --type rspec --pattern spec/services
          - bundle exec parallel_test --type rspec --pattern spec/types
          - bundle exec parallel_test --type rspec --pattern spec/validators
          - bundle exec parallel_test --type rspec --pattern spec/ --exclude-pattern 'spec/(cells|validators|types|services|requests|queries|presenters|permissions|models|lib|jobs|helpers|commands|controllers|events|forms|system)'
          - bundle exec parallel_test --type rspec --pattern spec/system --exclude-pattern spec/system/admin
          - bundle exec parallel_test --type rspec --pattern spec/system/admin
    needs: build_app
    name: Tests
    uses: ./.github/workflows/test_app.yml
    secrets: inherit
    with:
      working-directory: "decidim-proposals"
      test_command: ${{ matrix.test-command }}


